Fix xnio version mismatch
Without forcing the version, IntelliJ uses 3.3.8 which results in a Exception:
java.lang.AbstractMethodError: Receiver class org.xnio.nio.NioXnio does not define or inherit an implementation of the resolved method 'abstract org.xnio.XnioWorker createWorker(java.lang.ThreadGroup, org.xnio.OptionMap, java.lang.Runnable)' of abstract class org.xnio.Xnio.

Spring boot plugin applies different versions of undertow to the
compile and runtime classpath which require different versions of
xnio-api.